# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # Maintain Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    # Limit the number of open pull requests for version updates
    open-pull-requests-limit: 10
    # Group all patch updates into a single PR
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
    # Add labels to PRs for easier categorization
    labels:
      - "dependencies"
      - "rust"
    # Ignore major version updates for stability (can be reviewed manually)
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Commit message configuration
    commit-message:
      prefix: "deps"
      include: "scope"

  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
