# Cross.toml configuration for cross-compilation
#
# This configuration addresses GCC bug 95189 (memcmp bug) which affects GCC 9.x
# found in the default cross-rs images based on Ubuntu 20.04.
#
# The aws-lc-rs crate detects affected GCC versions and fails the build.
# Solution: Use edge images from cross-rs which use Ubuntu 22.04+ with GCC 11+
# (the bug was fixed in GCC 10.3+)

[build.env]
passthrough = [
    # Allow aws-lc-sys to receive custom compiler flags if needed
    "AWS_LC_SYS_CMAKE_BUILDER",
    "AWS_LC_SYS_EXTERNAL_BINDGEN",
]

[target.x86_64-unknown-linux-gnu]
# Use edge image with Ubuntu 22.04+ and GCC 11+
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:edge"

[target.aarch64-unknown-linux-gnu]
# Use edge image with Ubuntu 22.04+ and GCC 11+
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge"
