use std;

use tag::Tag;

/// Error types generated by this implementation
#[derive(Debug)]
pub enum Error {
    /// The associated tag was added to an `RtMessage` in non-increasing order.
    TagNotStrictlyIncreasing(Tag),

    /// Encoding failed. The associated `std::io::Error` should provide more information.
    EncodingFailure(std::io::Error),
}

impl From<std::io::Error> for Error {
    fn from(err: std::io::Error) -> Self {
        Error::EncodingFailure(err)
    }
}
